# Generated by Django 5.2 on 2025-05-18 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("idosos", "0002_idoso_foto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "idoso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="idosos.idoso"
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="idosos.responsavel",
                    ),
                ),
            ],
        ),
    ]
