# Generated by Django 5.2 on 2025-05-17 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estoque", "0003_rename_produto_imagem_remedio_alter_imagem_imagem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Idoso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("endereco", models.TextField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "remedios",
                    models.ManyToManyField(
                        blank=True, related_name="idosos_em_uso", to="estoque.remedio"
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idosos",
                        to="idosos.responsavel",
                    ),
                ),
            ],
        ),
    ]
