# Generated by Django 5.2 on 2025-05-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("idosos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idoso",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_idosos/"),
        ),
    ]
