# Generated by Django 5.2 on 2025-05-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="cargo",
            field=models.CharField(
                choices=[("G", "Gerente"), ("U", "Usuario")], max_length=1
            ),
        ),
    ]
